### ISSUE TITLE
Change console command to get links

### ISSUE THREAD

**Issue by tucq88** [ellerbrock/egghead-video-download#1]
Currently we're using : 
`document.querySelectorAll('.title a').forEach(link => console.log(link.href))`
to get all egghead links. 
But if links are too long, it may be shorten to with `**..**` in the middle like form `this-is-a-very-long-url` to `this-is-..-long-url` so if you want to copy actual links you have to right click and copy which is wasting time

I suggest we change to
`document.querySelectorAll('.title a').forEach(link => console.dir(link.href))`
It will display the full URL in console log and your life is easier. 

![Example image](https://i.gyazo.com/8e2fcba28090f709f22d8f1971a3465c.png)

**Comment by ellerbrock** [comment]
@tucq88 Thanks for the tip. Looks like console.dir is not an official standard yet :https://developer.mozilla.org/en-US/docs/Web/API/Console/dir. To put the links in an Array should get a similar effect with better support?
What you think about something like that:

``` javascript
let a=[];document.querySelectorAll('.title a').forEach(l => a.push(l.href));console.log(a);
```

**Comment by ellerbrock** [comment]
@tucq88 

i played a bit around and find a better solution for lazy people like programmers :)
if you execute this snippet you get all the links directly in your clipboard and fixes also the problem with too long urls. does also not support all browsers http://caniuse.com/#feat=clipboard but looks right now for me like the way to go with the oneliner :)

``` javascript
let a=[];document.querySelectorAll('.title a').forEach(l => a.push(l.href));copy(a.join('\n'));
```

![](http://i.giphy.com/ZJlesIV8TnabS.gif)

**Comment by tucq88** [comment]
haha. Thanks you. That should be added to readme.

**Comment by ellerbrock** [comment]
@tucq88 done :)
also mentioned you in [line 37](https://github.com/ellerbrock/egghead-video-download#solution-2-print-the-collected-links-to-the-console-via-consoledir)
