### ISSUE TITLE
ERROR: insecure string pickle

### ISSUE THREAD

**Issue by CEOGavin** [ellerbrock/egghead-video-download#2]
I am trying to download -
https://egghead.io/lessons/javascript-redux-the-single-immutable-state-tree

But I get the following error -
[generic] javascript-redux-the-single-immutable-state-tree: Requesting header
WARNING: Falling back on generic information extractor.
[generic] javascript-redux-the-single-immutable-state-tree: Downloading webpage
[generic] javascript-redux-the-single-immutable-state-tree: Extracting information
[Wistia] k41wmxv1eg: Downloading JSON metadata
ERROR: insecure string pickle

Any idea what I may be missing?

PS - I have a paid account on EggHead.

**Comment by ellerbrock** [comment]
@CEOGavin the problem came from a python bug, you can find more infos and how to fix [here](https://github.com/rg3/youtube-dl/issues/6840)
