### ISSUE TITLE
--cookie

### ISSUE THREAD

**Issue by gartmeier** [ellerbrock/egghead-video-download#3]
to download pro content without clicking through the whole playlist and clicking download each time:
`youtube-dl -i -o "%(autonumber)s-%(title)s.%(ext)s" -a list.txt --cookie ../cookies.txt`

The cookies.txt can be downloaded via https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg?hl=en

**Comment by ellerbrock** [comment]
@torfeld6 thanks for the tip!
i added it to the readme and mention you there as well: <https://github.com/ellerbrock/egghead-video-download#download-for-pro-user>

![thx](http://i.giphy.com/3oEdva9BUHPIs2SkGk.gif)
