### ISSUE TITLE
can't download videos ?!

### ISSUE THREAD

**Issue by buamod** [ellerbrock/egghead-video-download#5]
$ get-links -u 'https://egghead./course.tld' -c ".playlist-lessons-list a" -o list.txt

(node:7105) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'red' of undefined
(node:7105) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ellerbrock** [comment]
you have an typo in the URL :1st_place_medal:
